### PR TITLE
Add Cloudflare DDNS and Calibre to templates

### PR DESCRIPTION
**Pull request by ModdedGamers**
This addresses #132 and adds the unofficial Cloudflare DDNS update docker image to the Selfhosted Templates.
This also adresses #158 to add Calibre.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#132: [APP REQUEST]: CloudFlare DDNS](https://issuehunt.io/repos/268890920/issues/132)
- [#158: [APP REQUEST]: Calibre](https://issuehunt.io/repos/268890920/issues/158)
---
</details>

### CODE REVIEW

**Comment by SelfhostedPro** [comment]
Looks like you missed a quotation in the name section on calibre (see the check that failed). Can you run it through a json validator to double check? I'll try to fix it when I'm near my computer if you don't get a chance to.

**Comment by ModdedGamers** [comment]
I'll get that ASAP

**Comment by ModdedGamers** [comment]
Fixed

**Comment by SelfhostedPro** [comment]
Everything looks good. Going to merge it to a Dev branch to test and once that looks good I'll merge it into master.

**Comment by SelfhostedPro** [comment]
Would you be able to test with the following url @ModdedGamers ? I don't have an instance of portainer that is working correctly currently.

https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/develop/Template/template.json

**Comment by ModdedGamers** [comment]
I'm not able to set an instance up right now, so I'll get to this ASAP.

**Comment by ModdedGamers** [comment]
Also, could you send me the rewards for these apps on issuehunt?

**Pull request merged**
