### PR TITLE
Add Dradis

### LINKED ISSUE #125: [APP REQUEST]: Dradis CE
[Issuehunt badges](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/issues/125)

### Dockerhub Link: ###
https://hub.docker.com/r/raesene/dradis

Their doesn't seem to be an official docker image of it. I believe this is the most reliable and recent image available.

### Description ###
Dradis Framework: Collaboration and reporting for IT Security teams http://dradisframework.org 

### Separate Database? ###
No

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [curator888 curator888](https://issuehunt.io/u/curator888) ($20.00)

### Submitted pull Requests
- [#182 Add Dradis](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/pull/182)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/SelfhostedPro/selfhosted_templates/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by bunysae**
Dradis is added. Fixes #125.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#125: [APP REQUEST]: Dradis CE](https://issuehunt.io/repos/268890920/issues/125)
---
</details>

### CODE REVIEW

**Comment by SelfhostedPro** [comment]
Can you pull the latest version and add this again? Looks like it's conflicting with another entry. I'll fix it myself in a few days if you don't get around to it.

**Comment by bunysae** [comment]
@SelfhostedPro
No problem. The merge conflict is resolved.

**Comment by bunysae** [comment]
@SelfhostedPro 
Could you transfer the bounty for this PR and for #182? Thanks

**Comment by SelfhostedPro** [comment]
Just rewarded. Didn't realized I need to manually do that. Thanks!

**Pull request merged**
